# Generated by Django 4.0.5 on 2022-06-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employers',
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
