# Generated by Django 4.0.5 on 2022-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_employers_employee_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='from_duration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='to_duration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
