# Generated by Django 4.0.5 on 2022-06-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_associates_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technoproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.associates')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.manager')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.technology')),
            ],
        ),
    ]
