# Generated by Django 4.0.4 on 2022-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_statusdurationofproject_phasedurationofproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='associates',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='associates',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='phasedurationofproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phasedurationofproject',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='technoproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='technoproject',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
