# Generated by Django 4.0.4 on 2022-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_associates_created_associates_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(blank=True, default=False, max_length=50),
            preserve_default=False,
        ),
    ]
