# Generated by Django 4.0.4 on 2022-06-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='phase',
        ),
    ]
