# Generated by Django 4.0.5 on 2022-06-17 18:11

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_project_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, default=project.models.get_status, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.status'),
        ),
    ]
