# Generated by Django 4.0.5 on 2022-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test',
            field=models.CharField(blank=True, default='Green', max_length=100, null=True),
        ),
    ]
