# Generated by Django 4.0.4 on 2022-07-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_associate_technology_associate_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
