# Generated by Django 4.0.4 on 2022-07-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_associate_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='joindate',
            field=models.DateField(null=True),
        ),
    ]
