# Generated by Django 4.0.4 on 2022-07-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_associate_created_alter_associate_joindate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.associate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
