# Generated by Django 4.0.4 on 2022-07-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_project_associate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='technology',
        ),
        migrations.AddField(
            model_name='associate',
            name='technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.technology'),
            preserve_default=False,
        ),
    ]
